### PR TITLE
Update tipo on line 53

### PR DESCRIPTION
**Pull request by angeldm**

### CODE REVIEW

**Comment by markshust** [comment]
I already took care of this just a couple hours ago :) Merged into all the branches. Thanks!

**Comment by angeldm** [comment]
Hello! I think it could be interesting put /root/.composer on a volume separated. It speed up the process next setups runs.

``` yaml
app:
  image: mageinferno/magento2-nginx:1.9.9-1
  ports:
    - "80:80"
  links:
    - magento-php-fpm
    - db
  volumes_from:
    - composer
    - appdata
    - cache
  environment:
    - APP_MAGE_MODE=default
    - VIRTUAL_HOST=192.168.0.71
    - PHP_HOST=magento-php-fpm
    - PHP_PORT=9000

cache:
  image: tianon/true
  volumes:
    - magento-data-cache:/var/cache/nginx

composer:
  container_name: magento-data-composer
  image: tianon/true
  volumes:
    - magento-data-composer:/root/.composer

appdata:
  image: tianon/true
  volumes:
    - magento-data-src:/src

"magento-php-fpm":
  image: mageinferno/magento2-php:7.0.2-fpm-0
  links:
    - db
  volumes_from:
    - composer  
    - appdata
  environment:
    - APP_MAGE_MODE=default
    - PHP_MEMORY_LIMIT=4G

db:
  image: mariadb:10.0
  ports:
    - "3306:3306"
  volumes_from:
    - dbdata
  environment:
    - MYSQL_ROOT_PASSWORD=Adp1224..
    - MYSQL_DATABASE=magento
    - MYSQL_USER=magento
    - MYSQL_PASSWORD=Adp1224..

dbdata:
  image: tianon/true
  volumes:
    - magento-data-db:/var/lib/mysql

setup:
  image: mageinferno/magento2-php:7.0.2-fpm-0
  command: /usr/local/bin/mage-setup
  links:
    - db
  volumes_from:
    - composer
    - appdata
  environment:
    - M2SETUP_DB_HOST=db
    - M2SETUP_DB_NAME=magento
    - M2SETUP_DB_USER=magento
    - M2SETUP_DB_PASSWORD=Adp1224..
    - M2SETUP_BASE_URL=http://192.168.0.71/
    - M2SETUP_ADMIN_FIRSTNAME=Admin
    - M2SETUP_ADMIN_LASTNAME=User
    - M2SETUP_ADMIN_EMAIL=dummy@gmail.com
    - M2SETUP_ADMIN_USER=admin
    - M2SETUP_ADMIN_PASSWORD=admin
    - M2SETUP_VERSION=2.0.0
    - M2SETUP_USE_SAMPLE_DATA=false
```

**Comment by markshust** [comment]
@angeldm thanks, I'm doing this but it's tied to `appdata`. I'll make a similar `composerdata`.

**Comment by markshust** [comment]
actually i take that back -- i think right now is the way it's best handled by default, mounting back to user's host directory from `appdata`.

```
appdata:
  image: tianon/true
  volumes:
    - /src
    - ~/.composer:/root/.composer
```

If users want another format they can feel free to modify to their use, but this does cache composer dir from user's host dir for every project.

**Pull request closed without merging**
